config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
root to:"todo_items#index"
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:activity, :descrption, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity %><br>
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :descrption %><br>
    <%= f.text_area :descrption %>
  </div>
  <div class="field">
    <%= f.check_box :status %>
    <%= f.label :status %><br>

  </div>
  <div class="actions">
    <%= f.submit%>
  </div>

<% end %>

app/views/todo_items/edit.html.erb
<center>
  <div class="row">
  <div class="col24s m12">
    <div class="card blue-grey darken-1">
           <div class="card-content white-text">
              <h1>Editing Todo Item</h1>

              <%= render 'form' %>

              <%= link_to 'Show', @todo_item,class:"btn waves-effect  blue lighten-4" %> |
              <%= link_to 'Back', todo_items_path,class:"btn waves-effect  blue lighten-4" %>
            </div>
      </div>
  </div>
</div>

</center>

app/views/todo_items/index.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
  <!--js-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">

<center>
<p id="notice"><%= notice %></p>
<h1>Todo Items</h1>



<form>
  <div class="row">
  <div class="col24s m12">
    <div class="card blue-grey darken-1">
           <div class="card-content white-text">
                <table>
                  <thead>
                      <tr>
                      <th>Activity</th>
                      <th>Descrption</th>
                      <th>Status</th>
                      <th colspan="3"></th>
                    </tr>

                  </thead>

                  <tbody>
                    <% @todo_items.each do |todo_item| %>
                      <tr>
                        <td><%= todo_item.activity %></td>
                        <td><%= todo_item.descrption %></td>
                        <td><%= todo_item.status %></td>
                        <td><%= link_to 'Show', todo_item,class:"btn waves-effect  blue lighten-4" %></td>
                        <td><%= link_to 'Edit', edit_todo_item_path(todo_item),class:"btn waves-effect  blue lighten-4" %></td>
                        <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' },class:"btn waves-effect  blue lighten-4" %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>

                <br>
                <%=  link_to 'New Todo item', new_todo_item_path, class:"btn waves-effect  blue lighten-4" %>
            </div>
        </div>
      </div>
  </div>
</form>
</center>

app/views/todo_items/new.html.erb
<center>
  <div class="row">
  <div class="col24s m12">
    <div class="card blue-grey darken-1">
           <div class="card-content white-text">
             <h1>New Todo Item</h1>

             <%= render 'form' %>

             <%= link_to 'Back', todo_items_path ,class:"btn waves-effect  blue lighten-4"%>
           </div>
    </div>
  </div>
</div>
</center>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>
<center>
  <div class="row">
    <div class="col24s m12">
      <div class="card blue-grey darken-1">
         <div class="card-content white-text">

            <p>
              <strong>Activity:</strong>
              <%= @todo_item.activity %>
            </p>

            <p>
              <strong>Descrption:</strong>
              <%= @todo_item.descrption %>
            </p>

            <p>
              <strong>Status:</strong>
              <%= @todo_item.status%>
            </p>

            <%= link_to 'Edit', edit_todo_item_path(@todo_item),class:"btn waves-effect  blue lighten-4" %> |
            <%= link_to 'Back', todo_items_path,class:"btn waves-effect  blue lighten-4" %>
        </div>
      </div>
    </div>
  </div>
</center>